/* Generated By:JavaCC: Do not edit this line. HtmlParserConstants.java */
package com.github.tagstream.impl;


/**
 * Token literal values and constants.
 * Generated by org.javacc.parser.OtherFilesGen#start()
 */
public interface HtmlParserConstants {

  /** End of File. */
  int EOF = 0;
  /** RegularExpression Id. */
  int SPACE = 1;
  /** RegularExpression Id. */
  int ATTR_IDENTIFIER = 2;
  /** RegularExpression Id. */
  int NAME_IDENTIFIER = 3;
  /** RegularExpression Id. */
  int QUOTED_STRING = 4;
  /** RegularExpression Id. */
  int TAG_END = 5;
  /** RegularExpression Id. */
  int TAG_SLASHEND = 6;
  /** RegularExpression Id. */
  int TAG_START = 7;
  /** RegularExpression Id. */
  int ENDTAG_START = 8;
  /** RegularExpression Id. */
  int COMMENT_START = 9;
  /** RegularExpression Id. */
  int DECL_START = 10;
  /** RegularExpression Id. */
  int RAWTEXT = 11;
  /** RegularExpression Id. */
  int TAG_NAME = 12;
  /** RegularExpression Id. */
  int LST_ERROR = 13;
  /** RegularExpression Id. */
  int ATTR_NAME = 15;
  /** RegularExpression Id. */
  int END_OF_TAG = 16;
  /** RegularExpression Id. */
  int ATTR_EQ = 17;
  /** RegularExpression Id. */
  int LIT_ERROR = 18;
  /** RegularExpression Id. */
  int ATTR_VAL = 19;
  /** RegularExpression Id. */
  int ERROR = 20;
  /** RegularExpression Id. */
  int COMMENT_END = 21;
  /** RegularExpression Id. */
  int COMMENT_WORD = 22;
  /** RegularExpression Id. */
  int DECL_TAG = 23;
  /** RegularExpression Id. */
  int DECL_ATTR = 24;
  /** RegularExpression Id. */
  int DECL_END = 25;

  /** Lexical state. */
  int DECLARATION = 0;
  /** Lexical state. */
  int COMMENT = 1;
  /** Lexical state. */
  int IN_DECLARATION = 2;
  /** Lexical state. */
  int ATTR_VALUE = 3;
  /** Lexical state. */
  int IN_TAG = 4;
  /** Lexical state. */
  int START_TAG = 5;
  /** Lexical state. */
  int DEFAULT = 6;

  /** Literal token values. */
  String[] tokenImage = {
    "<EOF>",
    "<SPACE>",
    "<ATTR_IDENTIFIER>",
    "<NAME_IDENTIFIER>",
    "<QUOTED_STRING>",
    "\">\"",
    "\"/>\"",
    "\"<\"",
    "\"</\"",
    "\"<!--\"",
    "\"<!\"",
    "<RAWTEXT>",
    "<TAG_NAME>",
    "<LST_ERROR>",
    "<token of kind 14>",
    "<ATTR_NAME>",
    "<END_OF_TAG>",
    "\"=\"",
    "<LIT_ERROR>",
    "<ATTR_VAL>",
    "<ERROR>",
    "\"-->\"",
    "<COMMENT_WORD>",
    "<DECL_TAG>",
    "<DECL_ATTR>",
    "<DECL_END>",
  };

}
